### ISSUE TITLE
Base II + Ableton

### ISSUE THREAD

**Issue by ClintH** [aumhaa/m4m8#4]
Hi.

I just got a Base II and set up Live 10.0.4 with the remote script here.

I think I've noticed a bug: launch mode/track controls from button one don't work when a MIDI track is selected. At the moment nothing happens when the button is used. It would be useful to be able to trigger a different clip on a MIDI track and especially toggle rec arm.

Thanks for putting in the work to port this stuff to Live 10!

**Comment by aumhaa** [comment]
Confirmed.  I'll try figure out what's going on and get a fix out soon, thanks for the report!

**Comment by aumhaa** [comment]
The problem you found should be fixed with the most current build.  There is still a problem with the User Mapping's layer bleeding through to keyboard/drumpad layers, I can't figure out exactly what's going on and probably won't have time to fix it for a couple of weeks, but I'll keep working on it.

**Comment by ClintH** [comment]
Thank you!
