### ISSUE TITLE
Stepper sampler parameters mapped incorrectly on central knobs

### ISSUE THREAD

**Issue by urecio** [aumhaa/m4m8#7]
Hi,

Not sure if it's an issue or not.
When using steppr:
- I press the third encoder on the top row.
- central pads turn pink
- I rotate the knob right bellow that encoder, and changes the param above it.
An example would be that I'm rotating the knob bellow the decay, but the decay gets changed.

Very nice work btw, thank you!

**Comment by aumhaa** [comment]
This is actually by design, because the top encoders in the CNTRLR_v2 script are used for global functions (like track navigation), as opposed to the v1 script where they were only used for mod functionality. 

It's unfortunate and awkward, I know, but it was necessary to make some compromises to accommodate the new functionality of the CNTRLR_v2 script.  You can get to the bottom knob functions by using the "shift" button (I think it's the second encoder button on the top).

There is the CNTRLR_retro script in m4m8 that more closely approximates the original CNTRLR_v1 script, but I never got around to documenting it.  Feel free to bug me (either here or via mail) if you want some info on how to get it working.

**Comment by urecio** [comment]
Yep it's a shame. Thanks for the info and again nice work.
